# Generated by Django 5.1.1 on 2024-11-03 12:18

import material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0002_alter_material_material_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="hardware_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="image",
            field=models.ImageField(
                default="",
                upload_to="materials_images/",
                validators=[material.models.validate_image_format],
            ),
            preserve_default=False,
        ),
    ]
