# Generated by Django 5.1.1 on 2024-11-05 06:04

import material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0003_material_hardware_name_alter_material_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials_images/",
                validators=[material.models.validate_image_format],
            ),
        ),
    ]
