# Generated by Django 5.1.1 on 2024-11-11 15:16

import material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0005_alter_material_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="image",
            field=models.ImageField(
                blank="true",
                null="true",
                upload_to="materials_images/",
                validators=[material.models.validate_image_format],
            ),
        ),
    ]
