# Generated by Django 5.1.1 on 2024-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
