# Generated by Django 5.1.1 on 2024-09-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='cart',
        ),
    ]
