# Generated by Django 5.1.1 on 2024-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_items_cart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
