# Generated by Django 5.1.1 on 2024-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_user_data_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_data',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
