# Generated by Django 5.1.1 on 2024-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('homeowner_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
