# Generated by Django 5.1.1 on 2024-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('Building materials', 'Building materials'), ('Finishing materials', 'Finishing materials'), ('Hardware and tools', 'Hardware and tools')], max_length=50)),
                ('material_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
